export enum ApplicationVariableEnum {
  DATABASE_DATABASE = 'DATABASE_NAME',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
}
